/**
 * Audit repository (§32 Monthly Audit).
 *
 * A monthly audit is a first-class object — not just a report.
 * It captures the system's best-effort interpretation of a period:
 * wins, failures, contradictions, patterns, risks and forward recommendations.
 *
 * Audits are generated by the analysis layer (Phase 12), not by UI directly.
 * Each audit references supportingEvidenceIds so its conclusions are traceable.
 */

import { dbGet, dbPut, dbGetAll, dbGetAllByIndex } from './db.js';

const STORE = 'audits';
const SCHEMA_VERSION = 1;

// ─── Helpers ───────────────────────────────────────────────────────────────────

function generateId() {
  return `audit_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

function now() {
  return new Date().toISOString();
}

// ─── Write ─────────────────────────────────────────────────────────────────────

/**
 * Persists a new Audit record.
 *
 * @param {{
 *   period:               { start: string, end: string },  — ISO 8601
 *   periodStart:          string,  — denormalized for index (= period.start)
 *   domains:              string[],
 *   evidenceCoverage:     Record<string, number>,
 *   scoreChanges?:        { domain: string, previous: number, current: number, delta: number }[],
 *   wins?:                string[],
 *   failures?:            string[],
 *   contradictions?:      string[],
 *   patterns?:            string[],
 *   risks?:               string[],
 *   recommendations?:     string[],
 *   nextPeriodFocus?:     string[],
 *   supportingEvidenceIds: string[],
 *   analysisVersion:      string,
 * }} fields
 * @returns {Promise<string>} The generated audit ID
 */
export async function addAudit(fields) {
  const ts = now();
  const record = {
    id:                   fields.id ?? generateId(),
    schemaVersion:        SCHEMA_VERSION,
    period:               fields.period,
    periodStart:          fields.period.start,   // denormalized for index lookup
    domains:              fields.domains          ?? [],
    evidenceCoverage:     fields.evidenceCoverage ?? {},
    scoreChanges:         fields.scoreChanges     ?? [],
    wins:                 fields.wins             ?? [],
    failures:             fields.failures         ?? [],
    contradictions:       fields.contradictions   ?? [],
    patterns:             fields.patterns         ?? [],
    risks:                fields.risks            ?? [],
    recommendations:      fields.recommendations  ?? [],
    findingStates:        fields.findingStates     ?? {},
    nextPeriodFocus:      fields.nextPeriodFocus  ?? [],
    supportingEvidenceIds: fields.supportingEvidenceIds ?? [],
    analysisVersion:      fields.analysisVersion,
    contextVersion:       fields.contextVersion ?? null,
    promptVersion:        fields.promptVersion ?? null,
    modelId:              fields.modelId ?? null,
    createdAt:            ts,
  };
  await dbPut(STORE, record);
  return record.id;
}

// ─── Read ──────────────────────────────────────────────────────────────────────

/**
 * Returns a single audit by ID, or null.
 * @param {string} id
 * @returns {Promise<object|null>}
 */
export async function getAudit(id) {
  return dbGet(STORE, id);
}

export async function updateAudit(id, fields) {
  const existing = await getAudit(id);
  if (!existing) throw new Error(`[auditRepository] Audit not found: ${id}`);
  const updated = { ...existing, ...fields, id, updatedAt: now() };
  await dbPut(STORE, updated);
  return updated;
}

/**
 * Returns all audits, sorted by period start ascending.
 * @returns {Promise<object[]>}
 */
export async function getAllAudits() {
  const all = await dbGetAll(STORE);
  return all.sort((a, b) => a.period.start.localeCompare(b.period.start));
}

/**
 * Returns the audit for a specific period start date, or null.
 * @param {string} periodStartISO  — ISO 8601
 * @returns {Promise<object|null>}
 */
export async function getAuditByPeriod(periodStartISO) {
  const matches = await dbGetAllByIndex(STORE, 'periodStart', periodStartISO);
  return matches.length > 0 ? matches[0] : null;
}

/**
 * Returns the most recent audit, or null if none exist.
 * @returns {Promise<object|null>}
 */
export async function getLatestAudit() {
  const all = await getAllAudits();
  return all.length > 0 ? all[all.length - 1] : null;
}
