import React, { useState, useEffect } from 'react';
import { ACCENT, THEMES } from '../constants.js';

/**
 * Insights Inbox (§33 Scheduled Analysis).
 * 
 * Displays passive insights generated by the background AnalysisScheduler.
 */
export default function InsightsInbox({ t, onQuestsChanged }) {
  const [insights, setInsights] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadInsights();
  }, []);

  async function loadInsights() {
    try {
      const { getActiveInsights } = await import('../database/insightsRepository.js');
      const active = await getActiveInsights();
      setInsights(active);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }

  async function handleDismiss(id) {
    try {
      const { updateInsightStatus } = await import('../database/insightsRepository.js');
      await updateInsightStatus(id, 'dismissed');
      setInsights(prev => prev.filter(i => i.id !== id));
    } catch (err) {
      console.error('Failed to dismiss insight:', err);
    }
  }

  async function handleApprove(insight) {
    try {
      const { approveAndApplyInsight } = await import('../core/ai/feedbackEngine.js');
      await approveAndApplyInsight(insight);
      setInsights(prev => prev.filter(i => i.id !== insight.id));
      if (onQuestsChanged) {
        onQuestsChanged();
      }
    } catch (err) {
      console.error('Failed to approve insight:', err);
      alert('Failed to approve insight: ' + err.message);
    }
  }

  if (loading) return null; // Invisible if loading

  if (insights.length === 0) {
    return (
      <div style={{ padding: '1rem', textAlign: 'center', color: t.muted, fontSize: '0.8rem', fontStyle: 'italic', background: t.subtleBg, border: `1px dashed ${t.border}` }}>
        No new scheduled insights.
      </div>
    );
  }

  const typeColors = {
    pattern: '#4a7ba6',
    contradiction: '#c1442c',
    risk: '#c1442c',
    win: '#4f8a5f',
    recommendation: '#d99a2b',
    summary: '#8a7060'
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
      {insights.map(insight => (
        <div key={insight.id} style={{ 
          borderLeft: `4px solid ${typeColors[insight.type] || ACCENT}`,
          borderTop: `1px solid ${t.border}`,
          borderRight: `1px solid ${t.border}`,
          borderBottom: `1px solid ${t.border}`,
          padding: '1.25rem',
          background: t.subtleBg,
          position: 'relative'
        }}>
          <button 
            onClick={() => handleDismiss(insight.id)}
            style={{
              position: 'absolute', top: '0.5rem', right: '0.5rem',
              background: 'transparent', border: 'none', color: t.muted,
              fontSize: '1.2rem', cursor: 'pointer'
            }}
            aria-label="Dismiss"
          >
            ×
          </button>

          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '0.75rem', paddingRight: '1rem' }}>
            <div style={{ fontFamily: 'monospace', fontSize: '0.65rem', letterSpacing: '0.15em', color: typeColors[insight.type] || ACCENT, textTransform: 'uppercase' }}>
              {insight.type}
            </div>
            {insight.confidence && (
              <div style={{ fontFamily: 'monospace', fontSize: '0.6rem', color: t.muted }}>
                Conf: {Math.round(insight.confidence * 100)}%
              </div>
            )}
          </div>

          <h3 style={{ margin: '0 0 1rem 0', fontSize: '1.1rem', lineHeight: 1.3 }}>{insight.title}</h3>
          
          <div style={{ fontSize: '0.9rem', lineHeight: 1.6, marginBottom: '1rem', color: t.pageText }}>
            {insight.statement}
          </div>

          {insight.recommendedActions && insight.recommendedActions.length > 0 && (
            <div style={{ marginTop: '0.75rem', marginBottom: '1rem' }}>
              <div style={{ fontFamily: 'monospace', fontSize: '0.6rem', letterSpacing: '0.1em', color: t.muted, textTransform: 'uppercase', marginBottom: '0.4rem' }}>
                Actions to Apply
              </div>
              <ul style={{ margin: 0, paddingLeft: '1.2rem', fontSize: '0.8rem', lineHeight: 1.4 }}>
                {insight.recommendedActions.map((action, idx) => (
                  <li key={idx} style={{ marginBottom: '0.2rem' }}>{action}</li>
                ))}
              </ul>
            </div>
          )}

          <div style={{ display: 'flex', gap: '0.5rem', marginTop: '1rem', borderTop: `1px solid ${t.borderFaint}`, paddingTop: '1rem' }}>
            <button 
              onClick={() => handleApprove(insight)}
              style={{
                padding: '0.5rem 1rem',
                background: '#4f8a5f',
                border: 'none',
                color: '#fff',
                fontFamily: 'monospace', fontSize: '0.65rem', letterSpacing: '0.1em', textTransform: 'uppercase',
                cursor: 'pointer', flex: 1
              }}
            >
              Approve & Apply
            </button>
            <button 
              onClick={() => handleDismiss(insight.id)}
              style={{
                padding: '0.5rem 1rem',
                background: 'transparent',
                border: `1px solid ${t.borderSoft}`,
                color: t.muted,
                fontFamily: 'monospace', fontSize: '0.65rem', letterSpacing: '0.1em', textTransform: 'uppercase',
                cursor: 'pointer', flex: 1
              }}
            >
              Dismiss
            </button>
          </div>
        </div>
      ))}
    </div>
  );
}
