/**
 * Decision schema factory (§16 Strategy Architecture).
 */

import { SCHEMA_VERSION } from '../version.js';

export function buildDecision(fields) {
  return {
    id: fields.id, // ID must be provided (generated by repo)
    schemaVersion: SCHEMA_VERSION,
    situation: fields.situation ?? '',
    objective: fields.objective ?? '',
    options: fields.options ?? [],
    chosenOption: fields.chosenOption ?? null,
    actualOutcome: fields.actualOutcome ?? null,
    lesson: fields.lesson ?? null,
    createdAt: fields.createdAt,
    updatedAt: fields.updatedAt,
  };
}
